//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Id_Pedido { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Id_Responsable { get; set; }
        public string StatusPedido { get; set; }
        public Nullable<int> Id_Mesa { get; set; }
    
        public virtual Mesa Mesa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
